services:
  # Веб-приложение
  - type: web
    name: warehouse-rental-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: warehouse-rental-db
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: UPLOAD_FOLDER
        value: static/uploads
      - key: MAX_CONTENT_LENGTH
        value: 16777216
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: REMEMBER_COOKIE_SECURE
        value: true
      - key: SESSION_COOKIE_HTTPONLY
        value: true
      - key: REMEMBER_COOKIE_HTTPONLY
        value: true
      - key: ITEMS_PER_PAGE
        value: 12

databases:
  # База данных PostgreSQL
  - name: warehouse-rental-db
    databaseName: warehouse_rental
    user: warehouse_user
    plan: free 